version: "3.6"

services:
    orchestrator:
        build: ./orchestrator
        ports:
            - "4000:4000"
        env_file:
            - ./orchestrator/.env
    app-service:
        build: ./services/app
        ports:
            - "4002:4002"
        env_file:
            - ./services/app/.env
    user-service:
        build: ./services/users
        ports:
            - "4001:4001"
        env_file:
            - ./services/users/.env